#----------------------------------------------- 容器运行时参数（不可配置项） -------------------------------------------#
# CRI socket path
cri_socket: >-
  {%- if container_manager == 'containerd' -%}
  unix:///var/run/containerd/containerd.sock
  {%- elif container_manager == 'docker' -%}
  unix:///var/run/cri-dockerd.sock
  {%- endif -%}