name: Base packages for arm64 
on:
  workflow_call:
    secrets:
      OSS_TOKEN:
      OSS_USERNAME:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install and configure minio client
      run: |
        sudo curl -sSLo /usr/bin/mc https://dl.min.io/client/mc/release/linux-amd64/mc
        sudo chmod +x /usr/bin/mc
        mc alias set oss https://files.saas.hand-china.com ${{ secrets.OSS_USERNAME }} ${{ secrets.OSS_TOKEN }}

    - name: Download packages for arm64
      run: |
        /bin/bash offline/download-others.sh arm64
        tar -czvf base.tgz base

    - name: Upload arm64 artifact to oss
      id: oss
      run: |
        mc cp --json base.tgz oss/kubeadm-ha/kubernetes-1.33.4-base-arm64.tgz 2>&1 | tee oss.log
        target=$(cat oss.log | jq -r 'select(.target)|.target')
        echo "::warning file=kubernetes-packages::https://files.saas.hand-china.com/${target#*/}"
